refactor: split unit tests
hstreamdb/hstreamdb-java pull request #177
Opened 2023-03-13 09:08 UTC by alissa-tung

2023-03-14 09:25 UTC, alissa-tung commented
r? @s12f

2023-03-15 10:04 UTC, s12f approved these changes

2023-03-15 10:46 UTC, daleiz requested changes

2023-03-15 10:46 UTC, daleiz commented on client/src/test/java/io/hstream/SubscriptionTest.java
> +  public void testBuilderMissingSubscriptionIdThrowsNullPointerException() {
.

2023-03-16 06:53 UTC, alissa-tung commented on client/src/test/java/io/hstream/SubscriptionTest.java
> +  public void testBuilderMissingSubscriptionIdThrowsNullPointerException() {
[0b2b94a](https://github.com/hstreamdb/hstreamdb-java/pull/177/commits/0b2b94a404f0d81d843443682facad393b317407)

2023-03-16 08:03 UTC, merged