fix: unit of requestTimeoutMs
hstreamdb/hstreamdb-java pull request #203
Opened 2023-04-27 09:43 UTC by alissa-tung

2023-04-27 09:43 UTC, alissa-tung commented
@daleiz @s12f

2023-04-28 02:11 UTC, daleiz requested changes

2023-04-28 02:11 UTC, daleiz commented on client/src/main/kotlin/io/hstream/impl/HStreamClientKtImpl.kt
> +    fun getCoroutineStubWithTimeoutSeconds(url: String, timeoutSeconds: Long = requestTimeoutMs * 1000): HStreamApiGrpcKt.HStreamApiCoroutineStub {
just remove this.

2023-04-28 03:31 UTC, daleiz approved these changes

2023-04-28 04:17 UTC, merged