Retry client `append` and `refactor` request when failed.
hstreamdb/hstreamdb-java pull request #40
Opened 2021-12-14 07:20 UTC by alissa-tung

2021-12-15 07:40 UTC, alissa-tung commented
I gonna simplify these stuff...

2021-12-15 09:17 UTC, alissa-tung commented
@daleiz

2021-12-16 08:56 UTC, daleiz commented
This method only retry blockingCall, but is not useful for asnycCall.

2021-12-16 08:58 UTC, daleiz requested changes
This method only retry blockingCall, but is not useful for asnycCall.

2021-12-16 09:35 UTC, closed without merging